//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidList
    {
        public int AuctionID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Bid { get; set; }
    
        public virtual Auction Auction { get; set; }
        public virtual Users Users { get; set; }
    }
}
