//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCommentary
    {
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Comment { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
