//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileCommentary
    {
        public int UserID { get; set; }
        public int RatedUserID { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Commentary { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
