//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EbayEntities : DbContext
    {
        public EbayEntities()
            : base("name=EbayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auction> Auction { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<OnSaleProducts> OnSaleProducts { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ShippingOptions> ShippingOptions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<BidList> BidList { get; set; }
        public virtual DbSet<ImageCatalog> ImageCatalog { get; set; }
        public virtual DbSet<Movements> Movements { get; set; }
        public virtual DbSet<ProductCommentary> ProductCommentary { get; set; }
        public virtual DbSet<ProductsSold> ProductsSold { get; set; }
        public virtual DbSet<ProfileCommentary> ProfileCommentary { get; set; }
    }
}
